raphael: fcm: add missing entries
https://gist.github.com/SebaUbuntu/ec053a00a9988eaea091fb1cc1f19324

ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.nxp.hardware.nfc@1.2::INqNfc/default
    vendor.qti.hardware.cvp@1.0::ICvp/cvphalservice
    vendor.qti.hardware.radio.lpa@1.2::IUimLpa/UimLpa0
    vendor.qti.hardware.radio.lpa@1.2::IUimLpa/UimLpa1
    vendor.qti.hardware.radio.qtiradio@2.7::IQtiRadio/slot1
    vendor.qti.hardware.radio.qtiradio@2.7::IQtiRadio/slot2
    vendor.qti.hardware.scve.objecttracker@1.0::IObjectTracker/objectTracker
    vendor.qti.hardware.scve.panorama@1.0::IPanoramaStitching/panoStitching
    vendor.qti.hardware.scve.panorama@1.0::IPanoramaTracking/panoTracking
    vendor.qti.hardware.sensorscalibrate@1.0::ISensorsCalibrate/default
    vendor.qti.hardware.wifi.wifilearner@1.0::IWifiStats/wifiStats
    vendor.qti.power.pasrmanager@1.0::IPasrManager/default
    vendor.qti.qspmhal@1.0::IQspmhal/default