raphael: bluetooth: Fix undefined PROPERTY_VALUE_MAX
 * vendor/qcom/opensource/commonsys/bluetooth_ext/system_bt_ext/bta/swb/bta_ag_swb.cc:142:14: error: use of undeclared identifier 'PROPERTY_VALUE_MAX'
   char value[PROPERTY_VALUE_MAX];

 * This reverts commit d4ff4a1baaa4ee69600e35bda61834dd99fb7f12.

Change-Id: Iaa9458296d71feacc88f5f04d7f5b99616115f23
Signed-off-by: Omkar Chandorkar <gotenksIN@aosip.dev>